/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SubmitTestRequest } from '../../models/submit-test-request';
import { SubmitTestResponse } from '../../models/submit-test-response';

export interface SubmitTest$Params {
  userTestId: number;
      body: SubmitTestRequest
}

export function submitTest(http: HttpClient, rootUrl: string, params: SubmitTest$Params, context?: HttpContext): Observable<StrictHttpResponse<SubmitTestResponse>> {
  const rb = new RequestBuilder(rootUrl, submitTest.PATH, 'post');
  if (params) {
    rb.path('userTestId', params.userTestId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SubmitTestResponse>;
    })
  );
}

submitTest.PATH = '/v1/user-tests/{userTestId}/submit-test';
