/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuestionCreateRequest } from '../../models/question-create-request';
import { QuestionResponse } from '../../models/question-response';

export interface CreateQuestion$Params {
      body: QuestionCreateRequest
}

export function createQuestion(http: HttpClient, rootUrl: string, params: CreateQuestion$Params, context?: HttpContext): Observable<StrictHttpResponse<QuestionResponse>> {
  const rb = new RequestBuilder(rootUrl, createQuestion.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<QuestionResponse>;
    })
  );
}

createQuestion.PATH = '/v2/admin/questions';
