spring:
  application:
    name: psk-full-stack
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api
application:
  file:
    upload-dir: uploads
