spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psk_full_stack_dev
    username: psk_user
    password: psk_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        hbm2ddl.auto: create-drop
    database: postgresql
  mail:
    host: ${EMAIL_HOST_NAME}
    port: 587
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: /tmp/uploads
  cors:
    origins: http://localhost:8088/,http://localhost:4200,http://localhost:8080/
server:
  port: 8088
google:
  calendar:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    refresh-token: ${GOOGLE_REFRESH_TOKEN}
    application-name: PSK Calendar
    therapist-email: ${THERAPIST_EMAIL}