services:
  postgres:
    container_name: postgres-sql-psk
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: psk-full-stack
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-psk
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  psk-api:
    container_name: psk-api
    image: psk/psk:1.0.0-f
    environment:
      EMAIL_HOST_NAME: ${EMAIL_HOST_NAME}
      EMAIL_USER_NAME: ${EMAIL_USER_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - 8088:8088
    volumes:
      - psk-api-storage:/app/uploads
    networks:
      - spring-demo
    depends_on:
      - postgres

  psk-ui:
    container_name: psk-ui
    image: psk/psk-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - psk-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  psk-api-storage:
    driver: local
