services:
  postgres:
    container_name: postgres-sql-psk
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: psk-full-stack
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-psk
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  psk-api:
    container_name: psk-api
    platform: linux/amd64
    build:
      context: ./psk-full-stack
      dockerfile: Dockerfile
    environment:
      EMAIL_HOST_NAME: ${EMAIL_HOST_NAME}
      EMAIL_USER_NAME: ${EMAIL_USER_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
      THERAPIST_EMAIL: ${THERAPIST_EMAIL}
    ports:
      - 8088:8088
    volumes:
      - psk-api-storage:/app/uploads
    networks:
      - spring-demo
    depends_on:
      - postgres

  psk-ui:
    container_name: psk-ui
    build:
      context: ./psk-ui
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - psk-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  psk-api-storage:
    driver: local