services:
  postgres:
    container_name: postgres-sql-psk
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: psk-full-stack
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5433
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-psk
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
