services:
  - type: web
    name: psk-backend
    env: docker
    plan: free
    rootDir: psk-full-stack
    dockerfilePath: Dockerfile
    buildCommand: docker build -t psk-backend .
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_HOST
        value: dpg-cts8qlbqf0us73dqcmu0-a.frankfurt-postgres.render.com
      - key: JDBC_DATABASE_PORT
        value: 5432
      - key: JDBC_DATABASE_NAME
        value: psk_fullstack_db
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: psk-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: psk-db
          property: password
      - key: EMAIL_HOST_NAME
        sync: false
      - key: EMAIL_USER_NAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: THERAPIST_EMAIL
        sync: false

  - type: web
    name: psk-frontend
    env: docker
    plan: free
    rootDir: psk-ui
    dockerfilePath: Dockerfile
    buildCommand: docker build -t psk-frontend .
    autoDeploy: false
    envVars:
      - key: API_URL
        value: https://psk-backend.onrender.com

databases:
  - name: psk-db
    region: frankfurt
    plan: free