services:
  - type: web
    name: psk-backend
    env: docker
    plan: free
    rootDir: psk-full-stack
    dockerfilePath: Dockerfile
    buildCommand: docker build -t psk-backend .
    autoDeploy: false
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JDBC_DATABASE_HOST
        sync: true
      - key: JDBC_DATABASE_PORT
        sync: true
      - key: JDBC_DATABASE_NAME
        sync: true
      - key: JDBC_DATABASE_USERNAME
        fromDatabase:
          name: psk-db
          property: user
      - key: JDBC_DATABASE_PASSWORD
        fromDatabase:
          name: psk-db
          property: password
      - key: EMAIL_HOST_NAME
        sync: true
      - key: EMAIL_USER_NAME
        sync: true
      - key: EMAIL_PASSWORD
        sync: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: true
      - key: GOOGLE_CLIENT_SECRET
        sync: true
      - key: GOOGLE_REFRESH_TOKEN
        sync: true
      - key: THERAPIST_EMAIL
        sync: true

databases:
  - name: psk-db
    region: frankfurt
    plan: free