/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminTestCommentResponse } from '../../models/admin-test-comment-response';

export interface GetCommentsByTestTemplate$Params {
  testTemplateId: number;
}

export function getCommentsByTestTemplate(http: HttpClient, rootUrl: string, params: GetCommentsByTestTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AdminTestCommentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getCommentsByTestTemplate.PATH, 'get');
  if (params) {
    rb.path('testTemplateId', params.testTemplateId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AdminTestCommentResponse>>;
    })
  );
}

getCommentsByTestTemplate.PATH = '/v2/admin/comments/test-template/{testTemplateId}';
