/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminTestCommentRequest } from '../../models/admin-test-comment-request';
import { AdminTestCommentResponse } from '../../models/admin-test-comment-response';

export interface UpdateTestTemplateComments$Params {
  testTemplateId: number;
      body: Array<AdminTestCommentRequest>
}

export function updateTestTemplateComments(http: HttpClient, rootUrl: string, params: UpdateTestTemplateComments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AdminTestCommentResponse>>> {
  const rb = new RequestBuilder(rootUrl, updateTestTemplateComments.PATH, 'put');
  if (params) {
    rb.path('testTemplateId', params.testTemplateId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AdminTestCommentResponse>>;
    })
  );
}

updateTestTemplateComments.PATH = '/v2/admin/comments/test-template/{testTemplateId}';
