/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScoringStrategyResponse } from '../../models/scoring-strategy-response';

export interface GetAllScoringStrategies$Params {
}

export function getAllScoringStrategies(http: HttpClient, rootUrl: string, params?: GetAllScoringStrategies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ScoringStrategyResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllScoringStrategies.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ScoringStrategyResponse>>;
    })
  );
}

getAllScoringStrategies.PATH = '/v2/admin/scoring/strategies';
