/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignTestRequest } from '../../models/assign-test-request';
import { UserTestResponse } from '../../models/user-test-response';

export interface AssignTest$Params {
      body: AssignTestRequest
}

export function assignTest(http: HttpClient, rootUrl: string, params: AssignTest$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTestResponse>> {
  const rb = new RequestBuilder(rootUrl, assignTest.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserTestResponse>;
    })
  );
}

assignTest.PATH = '/v2/admin/user-tests/assign';
