/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';


export interface DeleteUserTest$Params {
  userTestId: number;
}

export function deleteUserTest(http: HttpClient, rootUrl: string, params: DeleteUserTest$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, deleteUserTest.PATH, 'delete');
  if (params) {
    rb.path('userTestId', params.userTestId, {});
  }

  return http.request(
    rb.build({responseType: 'text', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({body: undefined}) as StrictHttpResponse<void>;
    })
  );
}

deleteUserTest.PATH = '/v2/admin/user-tests/{userTestId}';
