/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAnswerResponse } from '../../models/user-answer-response';

export interface GetUserTestAnswers$Params {
  userTestId: number;
}

export function getUserTestAnswers(http: HttpClient, rootUrl: string, params: GetUserTestAnswers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserAnswerResponse>>> {
  const rb = new RequestBuilder(rootUrl, getUserTestAnswers.PATH, 'get');
  if (params) {
    rb.path('userTestId', params.userTestId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserAnswerResponse>>;
    })
  );
}

getUserTestAnswers.PATH = '/v2/admin/user-tests/{userTestId}/answers';
