/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserTestResponse } from '../../models/user-test-response';

export interface GetUserTest$Params {
  id: number;
}

export function getUserTest(http: HttpClient, rootUrl: string, params: GetUserTest$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTestResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserTest.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserTestResponse>;
    })
  );
}

getUserTest.PATH = '/v1/user-tests/{id}';
