/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestTemplateResponse } from '../../models/test-template-response';

export interface GetAllActiveTestTemplates$Params {
}

export function getAllActiveTestTemplates(http: HttpClient, rootUrl: string, params?: GetAllActiveTestTemplates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TestTemplateResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllActiveTestTemplates.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TestTemplateResponse>>;
    })
  );
}

getAllActiveTestTemplates.PATH = '/v3/public/tests';
