/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicTestAnswerCommentResponse } from '../../models/public-test-answer-comment-response';
import { PublicTestAnswerRequest } from '../../models/public-test-answer-request';

export interface CheckPublicTestAnswer$Params {
      body: PublicTestAnswerRequest
}

export function checkPublicTestAnswer(http: HttpClient, rootUrl: string, params: CheckPublicTestAnswer$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicTestAnswerCommentResponse>> {
  const rb = new RequestBuilder(rootUrl, checkPublicTestAnswer.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicTestAnswerCommentResponse>;
    })
  );
}

checkPublicTestAnswer.PATH = '/v3/test/check-answer';
