/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicTestResponse } from '../../models/public-test-response';

export interface GetPublicTestById$Params {
  id: number;
}

export function getPublicTestById(http: HttpClient, rootUrl: string, params: GetPublicTestById$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicTestResponse>> {
  const rb = new RequestBuilder(rootUrl, getPublicTestById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicTestResponse>;
    })
  );
}

getPublicTestById.PATH = '/v3/test/{id}';
