/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionResponseV2 } from '../../models/session-response-v-2';

export interface GetSessionByIdV2$Params {
  id: number;
  userId: number;
}

export function getSessionByIdV2(http: HttpClient, rootUrl: string, params: GetSessionByIdV2$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionResponseV2>> {
  const rb = new RequestBuilder(rootUrl, getSessionByIdV2.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionResponseV2>;
    })
  );
}

getSessionByIdV2.PATH = '/v2/sessions/{id}';
