/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseSessionResponseV2 } from '../../models/page-response-session-response-v-2';

export interface GetAllSessionsV2$Params {
  page: number;
  size: number;
}

export function getAllSessionsV2(http: HttpClient, rootUrl: string, params: GetAllSessionsV2$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseSessionResponseV2>> {
  const rb = new RequestBuilder(rootUrl, getAllSessionsV2.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseSessionResponseV2>;
    })
  );
}

getAllSessionsV2.PATH = '/v2/sessions/all';
