/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestTemplateCreateRequest } from '../../models/test-template-create-request';
import { TestTemplateResponse } from '../../models/test-template-response';

export interface CreateTestTemplate$Params {
      body: TestTemplateCreateRequest
}

export function createTestTemplate(http: HttpClient, rootUrl: string, params: CreateTestTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<TestTemplateResponse>> {
  const rb = new RequestBuilder(rootUrl, createTestTemplate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestTemplateResponse>;
    })
  );
}

createTestTemplate.PATH = '/v2/admin/test-templates';
