/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {TestTemplateResponse} from '../../models/test-template-response';

export interface GetAvailableTestTemplatesForUser$Params {
  userId: number;
}

export function getAvailableTestTemplatesForUser(http: HttpClient, rootUrl: string, params: GetAvailableTestTemplatesForUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TestTemplateResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAvailableTestTemplatesForUser.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({responseType: 'json', accept: 'application/json', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TestTemplateResponse>>;
    })
  );
}

getAvailableTestTemplatesForUser.PATH = '/v2/admin/test-templates/available-for-user/{userId}';
