/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestTemplateResponse } from '../../models/test-template-response';

export interface GetTestTemplateById1$Params {
  id: number;
}

export function getTestTemplateById1(http: HttpClient, rootUrl: string, params: GetTestTemplateById1$Params, context?: HttpContext): Observable<StrictHttpResponse<TestTemplateResponse>> {
  const rb = new RequestBuilder(rootUrl, getTestTemplateById1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestTemplateResponse>;
    })
  );
}

getTestTemplateById1.PATH = '/v2/admin/test-templates/{id}';
