/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TestTemplateResponse } from '../../models/test-template-response';
import { TestTemplateUpdateRequest } from '../../models/test-template-update-request';

export interface UpdateTestTemplate$Params {
  id: number;
      body: TestTemplateUpdateRequest
}

export function updateTestTemplate(http: HttpClient, rootUrl: string, params: UpdateTestTemplate$Params, context?: HttpContext): Observable<StrictHttpResponse<TestTemplateResponse>> {
  const rb = new RequestBuilder(rootUrl, updateTestTemplate.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TestTemplateResponse>;
    })
  );
}

updateTestTemplate.PATH = '/v2/admin/test-templates/{id}';
