/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { QuestionResponse } from '../../models/question-response';

export interface UpdateTestTemplateQuestions$Params {
  id: number;
      body: Array<QuestionResponse>
}

export function updateTestTemplateQuestions(http: HttpClient, rootUrl: string, params: UpdateTestTemplateQuestions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<QuestionResponse>>> {
  const rb = new RequestBuilder(rootUrl, updateTestTemplateQuestions.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<QuestionResponse>>;
    })
  );
}

updateTestTemplateQuestions.PATH = '/v2/admin/test-templates/{id}/questions';
