/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllScoringStrategies } from '../fn/scoring-admin/get-all-scoring-strategies';
import { GetAllScoringStrategies$Params } from '../fn/scoring-admin/get-all-scoring-strategies';
import { ScoringStrategyResponse } from '../models/scoring-strategy-response';


/**
 * Admin endpoints for managing scoring strategies
 */
@Injectable({ providedIn: 'root' })
export class ScoringAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllScoringStrategies()` */
  static readonly GetAllScoringStrategiesPath = '/v2/admin/scoring/strategies';

  /**
   * Get all available scoring strategies.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllScoringStrategies()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllScoringStrategies$Response(params?: GetAllScoringStrategies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ScoringStrategyResponse>>> {
    return getAllScoringStrategies(this.http, this.rootUrl, params, context);
  }

  /**
   * Get all available scoring strategies.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllScoringStrategies$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllScoringStrategies(params?: GetAllScoringStrategies$Params, context?: HttpContext): Observable<Array<ScoringStrategyResponse>> {
    return this.getAllScoringStrategies$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ScoringStrategyResponse>>): Array<ScoringStrategyResponse> => r.body)
    );
  }

}
