/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DailyCalendarResponse } from '../models/daily-calendar-response';
import { getWeeklyCalendar } from '../fn/session-controller-v-3/get-weekly-calendar';
import { GetWeeklyCalendar$Params } from '../fn/session-controller-v-3/get-weekly-calendar';

@Injectable({ providedIn: 'root' })
export class SessionControllerV3Service extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getWeeklyCalendar()` */
  static readonly GetWeeklyCalendarPath = '/v3/sessions/weekly-calendar';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWeeklyCalendar()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWeeklyCalendar$Response(params: GetWeeklyCalendar$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DailyCalendarResponse>>> {
    return getWeeklyCalendar(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWeeklyCalendar$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWeeklyCalendar(params: GetWeeklyCalendar$Params, context?: HttpContext): Observable<Array<DailyCalendarResponse>> {
    return this.getWeeklyCalendar$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DailyCalendarResponse>>): Array<DailyCalendarResponse> => r.body)
    );
  }

}
