/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { completeTest } from '../fn/user-test/complete-test';
import { CompleteTest$Params } from '../fn/user-test/complete-test';
import { getCurrentUserTests } from '../fn/user-test/get-current-user-tests';
import { GetCurrentUserTests$Params } from '../fn/user-test/get-current-user-tests';
import { getUserTest } from '../fn/user-test/get-user-test';
import { GetUserTest$Params } from '../fn/user-test/get-user-test';
import { startTest } from '../fn/user-test/start-test';
import { StartTest$Params } from '../fn/user-test/start-test';
import { UserTestListResponse } from '../models/user-test-list-response';
import { UserTestResponse } from '../models/user-test-response';


/**
 * User endpoints for managing assigned tests
 */
@Injectable({ providedIn: 'root' })
export class UserTestService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `startTest()` */
  static readonly StartTestPath = '/v1/user-tests/{id}/start';

  /**
   * Start test.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `startTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  startTest$Response(params: StartTest$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTestResponse>> {
    return startTest(this.http, this.rootUrl, params, context);
  }

  /**
   * Start test.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `startTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  startTest(params: StartTest$Params, context?: HttpContext): Observable<UserTestResponse> {
    return this.startTest$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserTestResponse>): UserTestResponse => r.body)
    );
  }

  /** Path part for operation `completeTest()` */
  static readonly CompleteTestPath = '/v1/user-tests/{id}/complete';

  /**
   * Complete test.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `completeTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  completeTest$Response(params: CompleteTest$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTestResponse>> {
    return completeTest(this.http, this.rootUrl, params, context);
  }

  /**
   * Complete test.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `completeTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  completeTest(params: CompleteTest$Params, context?: HttpContext): Observable<UserTestResponse> {
    return this.completeTest$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserTestResponse>): UserTestResponse => r.body)
    );
  }

  /** Path part for operation `getCurrentUserTests()` */
  static readonly GetCurrentUserTestsPath = '/v1/user-tests';

  /**
   * Get current user's tests.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCurrentUserTests()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserTests$Response(params?: GetCurrentUserTests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserTestListResponse>>> {
    return getCurrentUserTests(this.http, this.rootUrl, params, context);
  }

  /**
   * Get current user's tests.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCurrentUserTests$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCurrentUserTests(params?: GetCurrentUserTests$Params, context?: HttpContext): Observable<Array<UserTestListResponse>> {
    return this.getCurrentUserTests$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserTestListResponse>>): Array<UserTestListResponse> => r.body)
    );
  }

  /** Path part for operation `getUserTest()` */
  static readonly GetUserTestPath = '/v1/user-tests/{id}';

  /**
   * Get specific user test.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserTest()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserTest$Response(params: GetUserTest$Params, context?: HttpContext): Observable<StrictHttpResponse<UserTestResponse>> {
    return getUserTest(this.http, this.rootUrl, params, context);
  }

  /**
   * Get specific user test.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserTest$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserTest(params: GetUserTest$Params, context?: HttpContext): Observable<UserTestResponse> {
    return this.getUserTest$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserTestResponse>): UserTestResponse => r.body)
    );
  }

}
