/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminTestCommentRequest {
  commentId?: number;
  cover?: Array<string>;
  score?: number;
  text?: string;
  title?: string;
}
