/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminTestCommentResponse {
  commentId?: number;
  imageUrl?: string;
  score?: number;
  text?: string;
  title?: string;
}
