/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminTestCommentResponse } from '../models/admin-test-comment-response';
import { PublicQuestionAdminResponse } from '../models/public-question-admin-response';
export interface AdminTestResponse {
  comments?: Array<AdminTestCommentResponse>;
  cover?: Array<string>;
  id?: number;
  isActive?: boolean;
  questions?: Array<PublicQuestionAdminResponse>;
  subTitle?: string;
  title?: string;
}
