/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlogResponse {
  createdDate?: string;
  id?: number;
  imageUrl?: string;
  shareable?: boolean;
  subTitle?: string;
  text?: string;
  title?: string;
}
