/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlogRequest {
  shareable?: boolean;
  subTitle?: string;
  text?: string;
  title?: string;
}
