/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BlogResponse {
  cover?: Array<string>;
  createdDate?: string;
  id?: number;
  shareable?: boolean;
  subTitle?: string;
  text?: string;
  title?: string;
}
