/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MyAnswerQuestionRequest } from '../models/my-answer-question-request';
export interface MyAnswerRequest {
  questions?: Array<MyAnswerQuestionRequest>;
  testId?: number;
}
