/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MyChoiceResponse } from '../models/my-choice-response';
export interface MyQuestionResponse {
  choices?: Array<MyChoiceResponse>;
  id?: number;
  text?: string;
}
