/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MyQuestionResponse } from '../models/my-question-response';
export interface MyTestResponse {
  cover?: Array<string>;
  questions?: Array<MyQuestionResponse>;
  subTitle?: string;
  testId?: number;
  title?: string;
}
