/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {SessionResponseV2} from '../models/session-response-v-2';

export interface PageResponseSessionResponseV2 {
  content?: Array<SessionResponseV2>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
