/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserWithIncomingSessionResponse } from '../models/user-with-incoming-session-response';
export interface PageResponseUserWithIncomingSessionResponse {
  content?: Array<UserWithIncomingSessionResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
