/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {UserWithSessionResponse} from '../models/user-with-session-response';

export interface PageResponseUserWithSessionResponse {
  content?: Array<UserWithSessionResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
