/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SubmitAnswerRequest } from '../models/submit-answer-request';
export interface PublicTestSubmissionRequest {
  answers: Array<SubmitAnswerRequest>;
  personalNotes?: string;
}
