/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminTestCommentRequest } from '../models/admin-test-comment-request';
export interface PublicTestCommentListRequest {
  comments?: Array<AdminTestCommentRequest>;
  testId?: number;
}
