/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTestQuestionRequest } from '../models/public-test-question-request';
export interface PublicTestQuestionListRequest {
  publicTestQuestionRequestList?: Array<PublicTestQuestionRequest>;
  testId?: number;
}
