/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicChoiceAdminResponse } from '../models/public-choice-admin-response';
export interface PublicQuestionAdminResponse {
  id?: number;
  publicChoiceResponseList?: Array<PublicChoiceAdminResponse>;
  text?: string;
}
