/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {PublicChoiceResponse} from '../models/public-choice-response';

export interface PublicQuestionResponse {
  id?: number;
  publicChoiceResponseList?: Array<PublicChoiceResponse>;
  text?: string;
}
