/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {PublicQuestionAdminResponse} from '../models/public-question-admin-response';

export interface PublicTestAdminResponse {
  cover?: Array<string>;
  id?: number;
  isActive?: boolean;
  questions?: Array<PublicQuestionAdminResponse>;
  subTitle?: string;
  title?: string;
}
