/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicQuestionResponse } from '../models/public-question-response';
export interface PublicTestResponse {
  cover?: Array<string>;
  id?: number;
  questions?: Array<PublicQuestionResponse>;
  subTitle?: string;
  title?: string;
}
