/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {PublicTestAnswerQuestionRequest} from '../models/public-test-answer-question-request';

export interface PublicTestAnswerRequest {
  questions?: Array<PublicTestAnswerQuestionRequest>;
  testId?: number;
}
