/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicChoiceRequest } from '../models/public-choice-request';
export interface PublicTestQuestionRequest {
  id?: number;
  publicChoiceRequestList?: Array<PublicChoiceRequest>;
  text?: string;
}
