/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicTestRequest {
  isActive?: boolean;
  subTitle?: string;
  testId?: number;
  title?: string;
}
