/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicTestAnswerCommentResponse {
  cover?: Array<string>;
  text?: string;
  title?: string;
}
