/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuestionCreateRequest {
  choiceIds?: Array<number>;
  orderIndex?: number;
  testTemplateId: number;
  text: string;
}
