/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface QuestionUpdateRequest {
  choiceIds?: Array<number>;
  orderIndex?: number;
  text: string;
}
