/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScoringStrategyResponse {
  description?: string;
  name?: string;
  strategyName?: string;
}
