/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionResponse {
  date?: string;
  noteForUser?: string;
  sessionId?: number;
  sessionLink?: string;
  sessionStatus?:
    | 'AWAITING_THERAPIST_APPROVAL'
    | 'APPOINTMENT_SCHEDULED'
    | 'COMPLETED'
    | 'CANCELED'
    | 'UNAVAILABLE';
}
