/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserForSessionResponse } from '../models/user-for-session-response';
export interface SessionResponseV2 {
  date?: string;
  isPaid?: boolean;
  noteForPsychologist?: string;
  noteForUser?: string;
  sessionId?: number;
  sessionStatus?: 'AWAITING_PSYCHOLOGIST_APPROVAL' | 'APPOINTMENT_SCHEDULED' | 'COMPLETED' | 'CANCELED' | 'UNAVAILABLE';
  userForSessionResponse?: UserForSessionResponse;
}
