/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionResponse {
  date?: string;
  noteForUser?: string;
  sessionId?: number;
  sessionStatus?: 'AWAITING_PSYCHOLOGIST_APPROVAL' | 'AWAITING_PAYMENT' | 'AWAITING_PAYMENT_CONFIRMATION' | 'APPOINTMENT_SCHEDULED' | 'COMPLETED' | 'CANCELED' | 'UNAVAILABLE';
}
