/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionPsychologistNoteRequest {
  noteForPsychologist?: string;
  sessionId?: number;
}
