/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserAnswerResponse } from '../models/user-answer-response';
export interface SubmitTestResponse {
  completedAt?: string;
  isCompleted?: boolean;
  submittedAnswers?: Array<UserAnswerResponse>;
  userTestId?: number;
}
