/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TestTemplateUpdateRequest {
  imageUrl?: string;
  isActive?: boolean;
  subTitle?: string;
  title: string;
}
