/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TestTemplateResponse {
  createdBy?: string;
  createdDate?: string;
  id?: number;
  imagePath?: string;
  imageUrl?: string;
  isActive?: boolean;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  scoringStrategy?: 'SIMPLE_LINEAR' | 'WEIGHTED' | 'PERCENTAGE';
  subTitle?: string;
  title?: string;
}
