/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  birthYear?: string;
  email?: string;
  firstname?: string;
  lastname?: string;
  phoneNumber?: string;
}
