/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserCommentResponse } from '../models/user-comment-response';
import { UserQuestionResponse } from '../models/user-question-response';
export interface UserTestForAdminResponse {
  answerDistribution?: {
[key: string]: number;
};
  comments?: Array<UserCommentResponse>;
  imageUrl?: string;
  lastModifiedDate?: string;
  questions?: Array<UserQuestionResponse>;
  subTitle?: string;
  testId?: number;
  title?: string;
  userId?: number;
}
