/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserWithSessionResponse {
  firstname?: string;
  id?: number;
  lastname?: string;
  sessionIds?: Array<number>;
}
