/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionResponseV2 } from '../models/session-response-v-2';
export interface UserWithIncomingSessionResponse {
  firstname?: string;
  id?: number;
  lastname?: string;
  sessionResponse?: SessionResponseV2;
}
