/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserTestListResponse {
  assignedAt?: string;
  completedAt?: string;
  id?: number;
  isCompleted?: boolean;
  testTemplateId?: number;
  testTemplateImageUrl?: string;
  testTemplateSubTitle?: string;
  testTemplateTitle?: string;
  userEmail?: string;
  userFirstname?: string;
  userId?: number;
  userLastname?: string;
}
