/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserTestResponse {
  assignedAt?: string;
  assignedBy?: number;
  assignedByFirstname?: string;
  assignedByLastname?: string;
  completedAt?: string;
  createdBy?: number;
  createdDate?: string;
  id?: number;
  isCompleted?: boolean;
  lastModifiedBy?: number;
  lastModifiedDate?: string;
  personalNotes?: string;
  testTemplateId?: number;
  testTemplateImageUrl?: string;
  testTemplateSubTitle?: string;
  testTemplateTitle?: string;
  userEmail?: string;
  userFirstname?: string;
  userId?: number;
  userLastname?: string;
}
