/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserChoiceResponse } from '../models/user-choice-response';
export interface UserQuestionResponse {
  choices?: Array<UserChoiceResponse>;
  text?: string;
  userAnswer?: 'ANSWER_A' | 'ANSWER_B' | 'ANSWER_C' | 'ANSWER_D' | 'ANSWER_E';
}
